version: '3.8'

services:
    chrome:
        image: selenium/standalone-chrome:latest
        hostname: chrome
        container_name: chrome
        privileged: true
        shm_size: 2g
        healthcheck:
            test: curl -f http://localhost:4444
    my-python-app:
        build: .
        container_name: my-python-app
        depends_on:
            chrome:
                condition: service_healthy

networks:
    default:
        name: py-sel-network
        driver: bridge